### ISSUE TITLE
3 lines of professional title create too much blank space

### ISSUE THREAD

**Issue by dlkessler** [UWRealityLab/website#4]
When there are 3 lines of professional title, there's a huge amount of blank area before getting to the abstract and photo.  perhaps playing with the column widths will reduce professional titles to 2 lines?  - without making the talk titles too narrow?

**Comment by kimalexj** [comment]
<img width="1107" alt="Screen Shot 2019-03-29 at 10 37 51 PM" src="https://user-images.githubusercontent.com/22481898/55271986-54dd0b80-5273-11e9-826b-7d314c77f1f7.png">
@dlkessler @adityas 
I played around with the column widths a bit and at least for desktop made it look like this. Let me know if I should change anything 👍

**Comment by dlkessler** [comment]
@kimalexj @adityas  the right and left columns look good!  The center column (talk title) looks off-center.  No doubt as a result of widening the left column, so perhaps this can't be fixed?  IF it can be fixed  (professional info in 2 lines and talk title centred in the overall space) then please do.  IF it can't be fixed then so be it - getting his professional info onto 2 lines is more important.

**Comment by adityas** [comment]
I think this issue can be closed. It looks a lot better than before.
