### ISSUE TITLE
New hire! (Director of Education)

### ISSUE THREAD

**Issue by dlkessler** [UWRealityLab/website#47]
We've found a successor to Aditya!  Please replace Aditya's listing in the People page with this listing for John Akers.  Same format and location as Aditya's, but new title, photo, link, description.  
NOTE: Hold on to Aditya's photo and info somewhere in the site files - it might come in handy in the future (the public should not see Aditya's info anymore, but we should have it for future use)
  -- Name: John Akers
  -- Title: Director of Education
  -- Bio: John Akers is the Director of Education at the UW Reality Lab.  He received his Masters degree in Computer Science and Informatics from the University of Washington, where he focused on extended reality and user experience engineering, and worked in the Taskar Center for Accessible Technology researching accessible inputs for VR.
  -- Link: https://jakers.tech/index.html
  -- Photo:  available on the team drive at https://drive.google.com/open?id=1HvvcZwtt8T-C148ElhqMkOInTjRcRyUI  (NOTE: you will need to put in the same circular frame that holds each of our photos)

**Comment by dlkessler** [comment]
Hi Alex, meet John Akers, our new Director of Education.  He'll be looking at the website in teh coming weeks, and I'm adding him onto a couple of the existing issues (like this one)

**Comment by kimalexj** [comment]
Sorry i'll do this right away, I got caught up in my other tasks.
