### ISSUE TITLE
Updating courses

### ISSUE THREAD

**Issue by dlkessler** [UWRealityLab/website#50]
There are upcoming changes to the courses page.  Please set this up so we can update and publish them quickly once we're ready.  Yeah, I need to get more info for you.

Winter Quarter:
- 490v will be taught by Douglas Lanman.  Wednesdays and Fridays 4:30-5:50pm  TBA: location, official description, website.  It'll be a cool class, teaching students how to assemble a VR headset, so they appreciate what goes into them and why

Spring Quarter:
 - 481v (AR/VR Capstone) will be taught by Ira Kemelmacher
 - 576 will be taught by Steve Seitz. Tuesday & Thursday 3:00-4:20PM

**Comment by Jakersnorth** [comment]
just noting I'm making a branch for this to start testing out some ideas David and I had for how to reformat the page

**Comment by kimalexj** [comment]
Awesome I'd love to hear more about it when you have the chance. Additionally, nice to meet you!

**Comment by Jakersnorth** [comment]
I'd be happy to meet up at some point and talk about it further but the gist of the idea is modifying the course panels to include links to each offering of that course based on the quarter they were taught. Part of this would also be adding some indicator of which courses are going to be taught in the future compared to those which already happened.

**Comment by dlkessler** [comment]
use this link and create a course in the page for this class
https://courses.cs.washington.edu/courses/cse490v/20wi/

**Comment by dlkessler** [comment]
the webpage for Lanman's WinterQ class (490v) now has some graphics on it - you can steal one for the listing on our website's courses page. Thanks

**Comment by kimalexj** [comment]
Just added the new course but I'm going to leave this issue open to actually change more of the courses page

**Comment by kimalexj** [comment]
New Course Card Appearance:
<img width="1291" alt="Screen Shot 2019-11-29 at 2 38 52 PM" src="https://user-images.githubusercontent.com/22481898/69892022-0fffed80-12b6-11ea-981c-885d552f947c.png">

Video moved to bottom (left aligned):
<img width="1209" alt="Screen Shot 2019-11-29 at 2 38 59 PM" src="https://user-images.githubusercontent.com/22481898/69892024-11311a80-12b6-11ea-9646-3401c24ce1e9.png">

Hello! I hope you all had an amazing Thanksgiving. I just wanted to send these screenshots in here to ask for your opinions on the rearrangement. The idea with the *new* marking worked out for this format because I could replace the spot where the "past" offerings should be linked.

**Comment by Jakersnorth** [comment]
I think the layout looks fine it just needs more styling updates. Let's have all the link texts be underlined so it's more clear they're clickable. Having the most recent quarter and past offerings on the same line is fine but if there was some kind of visual separation between them that would help as well, and it should be fully written out "Past Offerings". Lastly don't forget to change the coloring on the quarter text. I hope you had a good break as well and thanks for working on this!

**Comment by Jakersnorth** [comment]
Hey Alex, the Reality Studio asked us to promote one of their classes next quarter (CSE490J: Virtual Reality Production for Storytelling) so it would be worth adding it to the course page. How's the work going on updating the design? I don't mind adding in more courses or touching things up but I don't want to do those updates in the middle of your redesign.

**Comment by kimalexj** [comment]
Hi Jake! I'm currently in the thick of finals but I'll push out preliminary
changes for now. They should be on the preview of the realitylab site. I
think the green color the current quarter looks alright and it gives the
feeling on interpretation that the class is still planned on being offered.
I additionally added the storytelling class to the home page and moved it
up next to virtual reality systems on the course page. Let me know if
anything needs to be changed or could use some fixing.
https://realitylab.uw.edu/preview/courses.html

**Comment by dlkessler** [comment]
John, this preview looks good to me; do you have any comment before Alex pushes it to the live site?

n.b. AFTER finals week is done there are some minor adjustments I would suggest, but all are less important than getting this updated now.  Those adjustments are:
 - Remove the word "Courses" from the top of the page
 - Slightly more space between the bottom of the graduate courses and the top of the undergraduate courses
 - Slightly more space between the bottom of the undergraduate courses and the top of the capstone video
 - Edit the descriptive sentence at the top of the page to read, "The UW Reality Lab, Reality Studio, and UW CSE offer academic courses..."
 - Add course numbers next to the name of each course.  Example: "VR/AR Capstone  (481v)"

**Comment by Jakersnorth** [comment]
Looks good to me. Let's push it to live and if I have some time this week I can make tweaks while Alex is finishing up finals.

**Comment by kimalexj** [comment]
Added all the additional changes since I just finished my finals, requested by @dlkessler, and they should be reflected on the main site. Have an amazing Christmas!

**Comment by kimalexj** [comment]
By that I mean winter break*
